data = [
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM FG-2",
    "REM FG-2",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20002126",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000922",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-01-15",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20002126",
    "REM DE-4",
    "REM DE-4",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20005756",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000924",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-02-05",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20005756",
    "Rapport exécuté sur 12 avr. 2022 13:17 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 1 sur 4",
    "",
]
[
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM GA-2",
    "REM GA-2",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20002129",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000919",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-01-15",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20002129",
    "REM AB-2",
    "REM AB-2",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20002127",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000921",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-01-15",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20002127",
    "Rapport exécuté sur 12 avr. 2022 13:17 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 2 sur 4",
    "",
]
[
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM BC-4",
    "REM BC-4",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20005755",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000925",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-02-05",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20005755",
    "REM CD-4",
    "REM CD-4",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20005757",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000923",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-02-05",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20005757",
    "Rapport exécuté sur 12 avr. 2022 13:17 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 3 sur 4",
    "",
]
[
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM EF-2",
    "REM EF-2",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20002128",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000920",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "18 sept. 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-01-15",
    "Desciption",
    "16",
    "Numéro de l'anneau / Number of the ring",
    "16",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "18 sept. 2020",
    "Numéro de série",
    "SG20002128",
    "Rapport exécuté sur 12 avr. 2022 13:17 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 4 sur 4",
    "",
]
