data2 = [
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM AB-1",
    "REM AB-1",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20022738",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000860",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "21 août 2020",
    "Propriétés supplémentaires",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "21 août 2020",
    "Numéro de série",
    "SG20022738",
    "REM DE-3",
    "REM DE-3",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20024200",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000882",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Francois Boisvert",
    "francois.boisvert@nouvlr.com",
    "21 août 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-04-30",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "21 août 2020",
    "Numéro de série",
    "SG20024200",
    "REM EF-1",
    "REM EF-1",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20022739",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "Rapport exécuté sur 12 avr. 2022 12:53 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 1 sur 3",
    "",
]
[
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000902",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "25 août 2020",
    "Propriétés supplémentaires",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "21 août 2020",
    "Numéro de série",
    "SG20022739",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM FG-1",
    "REM FG-1",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20022737",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000956",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "21 sept. 2020",
    "Propriétés supplémentaires",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "23 avr. 2020",
    "Numéro de série",
    "SG20022737",
    "REM GA-3",
    "REM GA-3",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20024205",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000817",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "20 août 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-04-30",
    "Rapport exécuté sur 12 avr. 2022 12:53 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 2 sur 3",
    "",
]
[
    "404100 Int. Stat. Technoparc Saint-",
    "Laurent à Stat. Aéroport",
    "Equipment report",
    "Voussoir – 7 éléments",
    "Desciption",
    "Replacement of broken",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "20 août 2020",
    "Numéro de série",
    "SG20024205",
    "Nom",
    "Description",
    "Emplacement",
    "Statut",
    "Code-barres",
    "ID de",
    "Nomb",
    "re",
    "total",
    "de",
    "probl",
    "Nom",
    "bre",
    "total",
    "de",
    "probl",
    "èmes",
    "ouve",
    "rts",
    "Dernière",
    "mise à jour",
    "REM CD-1",
    "REM CD-1",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20022736",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000957",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Vincent Murphy",
    "vincent.murphy@nouvlr.com",
    "21 sept. 2020",
    "Propriétés supplémentaires",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "23 avr. 2020",
    "Numéro de série",
    "SG20022736",
    "REM BC-3",
    "REM BC-3",
    "<Niveau supérieur>",
    "Segment",
    "installé",
    "SG20024199",
    "21 janv. 2021",
    "ID de liste de",
    "contrôle",
    "Nom",
    "Type",
    "Statut",
    "Auteur",
    "Date de",
    "création",
    "000881",
    "TP-Reception des Voussoirs",
    "AQ/CQ",
    "Fermé",
    "Francois Boisvert",
    "francois.boisvert@nouvlr.com",
    "21 août 2020",
    "Propriétés supplémentaires",
    "Date",
    "2020-04-30",
    "Desciption",
    "ok",
    "Numéro de l'anneau / Number of the ring",
    "11",
    "Date de Livraison",
    "12 avr. 2022",
    "Date de livraison",
    "21 août 2020",
    "Numéro de série",
    "SG20024199",
    "Rapport exécuté sur 12 avr. 2022 12:53 par Ryan Murdoch (ryan.murdoch@nouvlr.com)",
    "Page 3 sur 3",
    "",
]
